# Sharelatex Base Image (sharelatex/sharelatex-base)

FROM phusion/baseimage:0.11

ENV baseDir .

RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y build-essential wget nodejs unzip time imagemagick optipng strace nginx git python zlib1g-dev libpcre3-dev aspell aspell-en aspell-de aspell-es aspell-eu-es aspell-fr aspell-hu aspell-it aspell-lt aspell-lv aspell-pl aspell-pt-br aspell-ru aspell-sk aspell-uk python-pygments gnuplot libjpeg-dev 

WORKDIR /opt
RUN wget https://netix.dl.sourceforge.net/project/qpdf/qpdf/8.2.1/qpdf-8.2.1.tar.gz && tar zvxf qpdf-8.2.1.tar.gz
WORKDIR /opt/qpdf-8.2.1
RUN ./configure && make && make install && ldconfig

# Install TexLive
WORKDIR /opt
RUN wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz; \
	mkdir /install-tl-unx; \
	tar -xvf install-tl-unx.tar.gz -C /install-tl-unx --strip-components=1

RUN echo "selected_scheme scheme-basic" >> /install-tl-unx/texlive.profile; \
	/install-tl-unx/install-tl -profile /install-tl-unx/texlive.profile

RUN rm -r /install-tl-unx; \
	rm install-tl-unx.tar.gz

ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2018/bin/x86_64-linux/
RUN tlmgr install latexmk
RUN tlmgr install texcount

RUN npm install -g grunt-cli

# Set up sharelatex user and home directory
RUN adduser --system --group --home /var/www/sharelatex --no-create-home sharelatex; \
	mkdir -p /var/lib/sharelatex; \
	chown www-data:www-data /var/lib/sharelatex; \
	mkdir -p /var/log/sharelatex; \
	chown www-data:www-data /var/log/sharelatex; \
	mkdir -p /var/lib/sharelatex/data/template_files; \
	chown www-data:www-data /var/lib/sharelatex/data/template_files;

